### ISSUE TITLE
Improve Category Photo Presentation

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/whygriefmatters.org#70]
### Enhancement Description

At the moment the cover photos used on the Topic pages are not always presented in the best way.

Due to the current styling of the header, at certain viewport widths the header photo can take on strange dimensions and end up strangely cropped.
![CleanShot 2024-11-14 at 23 02 37@2x](https://github.com/user-attachments/assets/ab075a2f-7f04-4490-9058-9fac69983d15)

This can be remedied with proper art direction in Sanity, for example this is how the same header looks once the image hotspot has been set correctly:
![CleanShot 2024-11-14 at 23 09 59@2x](https://github.com/user-attachments/assets/32d2223a-c85a-48ab-8fa8-9d48ab8a667c)

For reference here is the unaltered photo as it stored inside Sanity:
![CleanShot 2024-11-14 at 23 04 54@2x](https://github.com/user-attachments/assets/ce8a8966-9e02-468c-be10-1fa9b3ece520)

In any case; we can do better!

What we should aim for instead is a responsive header that attempts to maintain an aspect ratio (somewhat) close to the original. We'll require some flexibility between viewport widths but attempting to maintain an image aspect ratio between 3:2 and 16:9 should ensure that the majority of images look great. Those that don't should be able to be corrected with good art direction (but we should be left with far fewer to correct).

### Additional Context

Examples of badly presented images are:
- https://whygriefmatters-org.pages.dev/loss-of-a-sibling/
- https://whygriefmatters-org.pages.dev/psychic-mediums-and-continuing-bonds
- https://whygriefmatters-org.pages.dev/do-men-grieve-differently

The component you want to target for these changes is `PageHeader`

### Acceptance Criteria

1. Overall UI design of header should be an improvement over what is there already
2. Aspect ratio of image should stay within the range of 3:2 to 16:9

Nice to haves:
1. Font scaling should be more responsive - probs be bigger on larger breakpoints like 'xl' etc.

### Suggested Solution

We should probably aim for something along these lines:
![image](https://github.com/user-attachments/assets/ef544718-75ab-4ba0-8ea2-bdcc684213ef)

However please feel free to experiment to come up with something better.

Also consider scaling up the font the larger screen sizes - it currently can look quite "sparse" at larger screen sizes

**Comment by aditya000028** [comment]
Hey @danlechambre , so I played around with the values of `bgPosX` and `bgPosY` in the file `PageHeader.astro`, by changing the default value of `0` to `0.5` . This change moves makes the center of the image visible essentially. 
I think this small change may be enough to tackle this problem. This way, no matter the screen size, the center of the image is always visible, which I think is what we want. I tested this change on different screen sizes and I noticed it performs well. I also do not think we need to manually set the width of each of the different image sizes when creating the url. Therefore, instead of having multiple [size]`ImgUrl` variables for each of the screen sizes, we can reduce it to just 1. 

Let me know your thoughts! Also, let me know if you would rather have me create a PR for this so it is easier for you to test the changes yourself. For an example, I have attached a screenshot below for you to see. 

Result on iPhone:
![image](https://github.com/user-attachments/assets/82f86d18-3b65-4347-8cf3-9fa26141b565)

Result on medium screen size:
![image](https://github.com/user-attachments/assets/15eda2fb-9578-4a38-965b-80347211032c)

Result on XL screen size:
![image](https://github.com/user-attachments/assets/1c00c77b-261f-4447-a0f8-32ec9f41f5c1)

**Comment by aditya000028** [comment]
Also @danlechambre , for the font scaling issue, I guess the fix should address the font scaling for the entire website, right? If so, I think this may require more changes, and it would probably be a good idea to create a separate issue for it. That way, we can also keep the changes for a separate issue local to that one branch. Regardless, I would be happy to take on that task. 

Let me know your thoughts.

**Comment by danlechambre** [comment]
Hey @aditya000028 good catch on the default value. Setting it to 0.5 will set the transform to 50% - so dead centre - which is a much better default than the top-left (how I had it), so please make this change.

This issue is a little more complex than just centering the image though I'm afraid. Whilst that's going to work on a good majority of cases, many images will have the subject in a different location. Over time we'll be employing more art direction via Sanity (in which case our defaults will rarely be needed) but the core issue will remain; those "letter box" like aspect ratios we're using on larger screen sizes will simply not do the original image justice.

If you can attempt to achieve something like the wireframe I've laid out that would be great.

In regards to the multiple image urls - if you do not specify the size when building the URL with Sanity img url builder then you'll download the full size image, in the 'Loss of a Sibling example that's a resolution of 5600x3733, which is far too large for web use. The pattern we're using here is a common one in that we should only load an image appropriate for the user's device and not waste bandwidth for us or them. In the "Loss of Sibling" example above the image that is loaded for mobile is only 33kB going up to 370kB for the full size desktop version, so you can see there's a massive saving to be had.

What might be worth noting is that this page layout used to have the images set up as "hero" type headers (similar to the homepage) which is why we're requesting an image of '2560' for 'xl'. As this is no longer the case, switching to <img srcset="..."> could be a good shout, and you should be able to bring the sizes down considerably. Depending on your design you may get away with setting only the width or only the height.

Finally, feel free to PR into draft if you're working through an approach - much easier to discuss when we've got the code in front of us 😊

**Comment by danlechambre** [comment]
Apologies, my use of the term 'font scaling' was misleading - I simply meant we might want to try out a larger font size at the larger screen breakpoints
